package wordy_idl;


/**
* wordy_idl/GameMenuServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/


// Interface for the Game Menu Servant object
public interface GameMenuServantOperations 
{
  int logIn (String username, String password) throws wordy_idl.InvalidPasswordException, wordy_idl.NoUserFoundException, wordy_idl.LoggedInException, wordy_idl.IncompleteCredentialsException;
  int createGame (int userId);
  int joinGame (int userId) throws wordy_idl.NoGameFoundException;
  String[][] getBestPlayers ();
  String[] getLongestWords ();
  void logOut (String username);
} // interface GameMenuServantOperations
