package wordy_idl;


/**
* wordy_idl/GameServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/


// Interface for a Game object when a player joins a game
public interface GameServantOperations 
{
  boolean gameCanStart () throws wordy_idl.NoPlayersJoinedException, wordy_idl.PendingGameException;
  boolean gameIsFinished ();
  void submitWord (int userId, String word) throws wordy_idl.InvalidWordException, wordy_idl.WordLengthException, wordy_idl.WrongLetterException;
  int checkPlayerCount ();
  long getRemainingPendingTime ();
  long getRemainingReadyTime ();
  long getRemainingRoundTime ();
  long getRemainingResultsTime ();
  char[] getLetters ();
} // interface GameServantOperations
