package wordy_idl;


/**
* wordy_idl/GameMenuServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/


// Interface for the Game Menu Servant object
public interface GameMenuServant extends GameMenuServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameMenuServant
