package wordy_idl;


/**
* wordy_idl/GameMenuServantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/


// Interface for the Game Menu Servant object
public abstract class GameMenuServantPOA extends org.omg.PortableServer.Servant
 implements wordy_idl.GameMenuServantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("logIn", new java.lang.Integer (0));
    _methods.put ("createGame", new java.lang.Integer (1));
    _methods.put ("joinGame", new java.lang.Integer (2));
    _methods.put ("getBestPlayers", new java.lang.Integer (3));
    _methods.put ("getLongestWords", new java.lang.Integer (4));
    _methods.put ("logOut", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // wordy_idl/GameMenuServant/logIn
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           int $result = (int)0;
           $result = this.logIn (username, password);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (wordy_idl.InvalidPasswordException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.InvalidPasswordExceptionHelper.write (out, $ex);
         } catch (wordy_idl.NoUserFoundException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.NoUserFoundExceptionHelper.write (out, $ex);
         } catch (wordy_idl.LoggedInException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.LoggedInExceptionHelper.write (out, $ex);
         } catch (wordy_idl.IncompleteCredentialsException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.IncompleteCredentialsExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // wordy_idl/GameMenuServant/createGame
       {
         int userId = in.read_long ();
         int $result = (int)0;
         $result = this.createGame (userId);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // wordy_idl/GameMenuServant/joinGame
       {
         try {
           int userId = in.read_long ();
           int $result = (int)0;
           $result = this.joinGame (userId);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (wordy_idl.NoGameFoundException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.NoGameFoundExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // wordy_idl/GameMenuServant/getBestPlayers
       {
         String $result[][] = null;
         $result = this.getBestPlayers ();
         out = $rh.createReply();
         wordy_idl.bestPlayersHelper.write (out, $result);
         break;
       }

       case 4:  // wordy_idl/GameMenuServant/getLongestWords
       {
         String $result[] = null;
         $result = this.getLongestWords ();
         out = $rh.createReply();
         wordy_idl.longestWordsHelper.write (out, $result);
         break;
       }

       case 5:  // wordy_idl/GameMenuServant/logOut
       {
         String username = in.read_string ();
         this.logOut (username);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:wordy_idl/GameMenuServant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameMenuServant _this() 
  {
    return GameMenuServantHelper.narrow(
    super._this_object());
  }

  public GameMenuServant _this(org.omg.CORBA.ORB orb) 
  {
    return GameMenuServantHelper.narrow(
    super._this_object(orb));
  }


} // class GameMenuServantPOA
