package wordy_idl;


/**
* wordy_idl/IncompleteCredentialsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:04 AM SGT
*/

public final class IncompleteCredentialsException extends org.omg.CORBA.UserException
{

  public IncompleteCredentialsException ()
  {
    super(IncompleteCredentialsExceptionHelper.id());
  } // ctor


  public IncompleteCredentialsException (String $reason)
  {
    super(IncompleteCredentialsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class IncompleteCredentialsException
