package wordy_idl;


/**
* wordy_idl/LoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 4:30:44 PM SGT
*/

public final class LoggedInException extends org.omg.CORBA.UserException
{

  public LoggedInException ()
  {
    super(LoggedInExceptionHelper.id());
  } // ctor


  public LoggedInException (String $reason)
  {
    super(LoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class LoggedInException
