package wordy_idl;


/**
* wordy_idl/playerRecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/


// Definitions for the list of strings pertaining to the best players and longest words
public final class playerRecordHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public playerRecordHolder ()
  {
  }

  public playerRecordHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordy_idl.playerRecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordy_idl.playerRecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordy_idl.playerRecordHelper.type ();
  }

}
