package wordy_idl;

/**
* wordy_idl/GameMenuServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 4:30:44 PM SGT
*/


// Interface for the Game Menu Servant object
public final class GameMenuServantHolder implements org.omg.CORBA.portable.Streamable
{
  public GameMenuServant value = null;

  public GameMenuServantHolder ()
  {
  }

  public GameMenuServantHolder (GameMenuServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameMenuServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameMenuServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameMenuServantHelper.type ();
  }

}
