package wordy_idl;


/**
* wordy_idl/GameMenuServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 8:10:20 AM SGT
*/

public interface GameMenuServantOperations 
{
  void logIn (String username, String password) throws InvalidPasswordException, NoUserFoundException, LoggedInException;
  void startGame (int userId) throws NoPlayersJoinedException;
  int joinGame (int userId) throws NoGameFoundException;
  String[] getBestPlayers ();
  String[] getLongestWords ();
} // interface GameMenuServantOperations
