package wordy_idl;

/**
* wordy_idl/GameServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/


// Interface for a Game object when a player joins a game
public final class GameServantHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServant value = null;

  public GameServantHolder ()
  {
  }

  public GameServantHolder (GameServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServantHelper.type ();
  }

}
