package wordy_idl;

/**
* wordy_idl/InvalidPasswordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 8:10:20 AM SGT
*/

public final class InvalidPasswordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidPasswordException value = null;

  public InvalidPasswordExceptionHolder ()
  {
  }

  public InvalidPasswordExceptionHolder (InvalidPasswordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidPasswordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidPasswordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidPasswordExceptionHelper.type ();
  }

}
