package wordy_idl;

/**
* wordy_idl/LoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 8:10:20 AM SGT
*/

public final class LoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public LoggedInException value = null;

  public LoggedInExceptionHolder ()
  {
  }

  public LoggedInExceptionHolder (LoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoggedInExceptionHelper.type ();
  }

}
