package wordy_idl;


/**
* wordy_idl/longestWordsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 8:10:20 AM SGT
*/

public final class longestWordsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public longestWordsHolder ()
  {
  }

  public longestWordsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = longestWordsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    longestWordsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return longestWordsHelper.type ();
  }

}
