package wordy_idl;


/**
* wordy_idl/NoPlayersJoinedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/

public final class NoPlayersJoinedException extends org.omg.CORBA.UserException
{

  public NoPlayersJoinedException ()
  {
    super(NoPlayersJoinedExceptionHelper.id());
  } // ctor


  public NoPlayersJoinedException (String $reason)
  {
    super(NoPlayersJoinedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoPlayersJoinedException
