package wordy_idl;

/**
* wordy_idl/PendingGameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/

public final class PendingGameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PendingGameException value = null;

  public PendingGameExceptionHolder ()
  {
  }

  public PendingGameExceptionHolder (PendingGameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PendingGameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PendingGameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PendingGameExceptionHelper.type ();
  }

}
