package wordy_idl;

/**
* wordy_idl/WordLengthExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/

public final class WordLengthExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordLengthException value = null;

  public WordLengthExceptionHolder ()
  {
  }

  public WordLengthExceptionHolder (WordLengthException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordLengthExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordLengthExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordLengthExceptionHelper.type ();
  }

}
