package wordy_idl;

/**
* wordy_idl/WrongLetterExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 10, 2023 8:44:05 AM SGT
*/

public final class WrongLetterExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WrongLetterException value = null;

  public WrongLetterExceptionHolder ()
  {
  }

  public WrongLetterExceptionHolder (WrongLetterException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WrongLetterExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WrongLetterExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WrongLetterExceptionHelper.type ();
  }

}
