package wordy_idl;


/**
* wordy_idl/GameMenuServant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 4:30:44 PM SGT
*/


// Interface for the Game Menu Servant object
public interface GameMenuServant extends GameMenuServantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameMenuServant
