package wordy_idl;


/**
* wordy_idl/NoGameFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 8:10:20 AM SGT
*/

public final class NoGameFoundException extends org.omg.CORBA.UserException
{

  public NoGameFoundException ()
  {
    super(NoGameFoundExceptionHelper.id());
  } // ctor


  public NoGameFoundException (String $reason)
  {
    super(NoGameFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoGameFoundException
