package wordy_idl;


/**
* wordy_idl/NoUserFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Monday, May 1, 2023 4:30:44 PM SGT
*/

public final class NoUserFoundException extends org.omg.CORBA.UserException
{

  public NoUserFoundException ()
  {
    super(NoUserFoundExceptionHelper.id());
  } // ctor


  public NoUserFoundException (String $reason)
  {
    super(NoUserFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoUserFoundException
